export const Photos = [
    {
        id:"0",
        src:"./src/assets/figma1.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"1",
        src:"./src/assets/figma2.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"2",
        src:"./src/assets/figma3.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"3",
        src:"./src/assets/graphics1.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"4",
        src:"./src/assets/graphics2.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"5",
        src:"./src/assets/graphics3.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"6",
        src:"./src/assets/graphics4.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"7",
        src:"./src/assets/graphics5.png",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"8",
        src:"./src/assets/art1.jpg",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"9",
        src:"./src/assets/art2.jpg",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"10",
        src:"./src/assets/art3.jpg",
        url:"",
        alt:"",
        label:""
    },
    {
        id:"11",
        src:"./src/assets/art4.jpg",
        url:"",
        alt:"",
        label:""
    },
]